name: forreuse

on:
  workflow_dispatch:
  workflow_call:

jobs:
  demo:
    name: This job is intended for reuse.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Say hello
        run: echo "Hello"
