name: reuse

on:
  push:
    branches:
      - "**"

jobs:
  demo:
    name: This job is intended to reuse another workflow.
    # runs-on: ubuntu-latest

    uses: ./.github/workflows/forreuse.yml

  post-demo:
    name: Run post steps after reusing another workflow
    runs-on: ubuntu-latest
    steps:
      - name: Postecho
      run: echo "Goodbye"
