name: reuse

on:
  push:
    branches:
      - "**"
      - "!master"
      - "![0-9]+.[0-9]+.x"

jobs:
  demo:
    name: This job is intended to reuse another workflow.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Reuse
        uses: ./for-reuse.yml
